package lumaceon.mods.clockworkphase2.lib;

public enum GUIs
{
    ASSEMBLY_TABLE, TEMPORAL_EXCAVATOR,
    CLOCKWORK_FURNACE, CLOCKWORK_ALLOY_FURNACE, CLOCKWORK_CRUSHER, CLOCKWORK_CRYSTALLIZER,
    LIFEFORM_CONSTRUCTOR
}
