@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package lumaceon.mods.clockworkphase2.block.temporal;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;